DROP TABLE IF EXISTS superstore_orders;

CREATE TABLE superstore_orders (
    row_id INT,
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(30),
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(100),
    state_province VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales NUMERIC(12,2),
    quantity INT,
    discount NUMERIC(5,2),
    profit NUMERIC(12,2),
    order_year INT,
    order_month VARCHAR(15),
    profit_margin NUMERIC(10,4),
    delivery_days INT,
    order_status VARCHAR(20)
);

SHOW data_directory;


SELECT column_name
FROM information_schema.columns
WHERE table_name = 'superstore_orders';


COPY superstore_orders
FROM 'C:/Program Files/PostgreSQL/17/data/base/QuickCommerce_Cleaned.csv'
WITH (
    FORMAT CSV,
    HEADER true,
    DELIMITER ',',
    QUOTE '"',
    ESCAPE '\'
);


SELECT * FROM superstore_orders


--THE TOTAL REVENUE GENERATED BY THE COMPANY
SELECT ROUND(SUM(sales),2) AS total_sales
FROM superstore_orders


--THE PRIOFIT THE COMPANY EARNED AFTER SALES 
SELECT ROUND(SUM(profit),2) AS total_profit
FROM superstore_orders


--TOTAL UNIQUE ORDERS PLACED BY THE CUSTOMERS
SELECT COUNT(DISTINCT order_id) AS total_order
FROM superstore_orders


--VIP CUSTOMERS CONTRIBUTING MAX REVENUE
SELECT customer_name,ROUND(SUM(sales),2) AS sales
FROM superstore_orders
GROUP BY customer_name
ORDER BY sales DESC
LIMIT 10


--BEST SELLING PRODUCTS
SELECT product_name,ROUND(SUM(sales),2) AS sales
FROM superstore_orders
GROUP BY product_name
ORDER BY sales DESC
LIMIT 10


--CATEGORIES WHICH GENERATE MAX REVENUE
SELECT category ,ROUND (SUM(sales),2) AS sales
FROM superstore_orders
GROUP BY category
ORDER BY sales DESC


--MOST PROFITABLE REGION
SELECT region ,ROUND (SUM(profit),2) AS profit
FROM superstore_orders
GROUP BY region
ORDER BY profit DESC


--HOW MANY DAYS DOES IT TAKE TO DEKIVER AN ORER AFTER PLACED
SELECT ROUND (AVG(delivery_days),2) AS avg_delivery_days
FROM superstore_orders


--COUNT ORDERS BASED ON STATUS(TRACK SERVICE QUALITY)
SELECT order_status,
COUNT(*) AS orders
FROM superstore_orders
GROUP BY order_status


--PEAK SALES MONTHS
SELECT order_month,
ROUND (SUM(sales),2) AS sales
FROM superstore_orders
GROUP BY order_month
ORDER BY sales DESC






